# Generated by Django 4.2.8 on 2024-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='client_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
